[project]
urls = { Repository = "https://github.com/lumina37/rotate-captcha-crack" }
name = "rotate-captcha-crack"
readme = "README.md"
requires-python = ">=3.9,<3.13"
authors = [{ name = "lumina37", email = "starry.qvq@gmail.com" }]
dependencies = [
    "matplotlib>=3.4,<4",
    "tqdm>=4,<5",
    "tomli>=2.0.0,<3;python_version<'3.11'",
    "torch>=1.11",
    "torchvision>=0.12.0",
]
dynamic = ["version"]

[project.optional-dependencies]
server = ["aiohttp", "httpx[cli]"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "rotate_captcha_crack/__version__.py"

[tool.rye]
managed = true

[[tool.rye.sources]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu124/"

[tool.ruff]
line-length = 120
target-version = "py38"

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "YTT",
    "ASYNC",
    "B",
    "A",
    "COM",
    "C4",
    "FA",
    "PIE",
    "PT",
    "RSE",
    "NPY",
    "PERF",
    "FURB",
]
ignore = ["E402", "E501", "COM812"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
